# Generated by Django 4.2.7 on 2026-07-03 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='ETB', max_length=3)),
                ('payment_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('telebirr', 'Telebirr'), ('chapa', 'Chapa')], default='bank', max_length=20)),
                ('bank_account_name', models.CharField(blank=True, default='', max_length=100)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=50)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('telebirr_phone', models.CharField(blank=True, default='', max_length=20)),
                ('chapa_email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processed', 'Processed'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('user_notes', models.TextField(blank=True, default='')),
                ('transaction_reference', models.CharField(blank=True, default='', max_length=100)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_requests',
            },
        ),
        migrations.CreateModel(
            name='Royalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='royalties', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='royalties', to='books.book')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='royalties', to='payments.purchase')),
            ],
            options={
                'db_table': 'royalties',
                'indexes': [models.Index(fields=['author', 'status'], name='royalties_author__c40d66_idx'), models.Index(fields=['book', 'status'], name='royalties_book_id_a39c14_idx'), models.Index(fields=['payment_date'], name='royalties_payment_4423a9_idx'), models.Index(fields=['period_start', 'period_end'], name='royalties_period__e23a9a_idx')],
            },
        ),
    ]
