# Generated by Django 4.2.7 on 2026-08-11 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Gross purchase amount', max_digits=10)),
                ('author_royalty', models.DecimalField(decimal_places=2, default=0.0, help_text="Author's royalty amount (before tax)", max_digits=10)),
                ('abrehot_share', models.DecimalField(decimal_places=2, default=0.0, help_text='Abrehot platform share', max_digits=10)),
                ('abrehot_share_rate', models.DecimalField(decimal_places=2, default=30.0, help_text='Abrehot share percentage', max_digits=5)),
                ('royalty_rate', models.DecimalField(decimal_places=2, default=70.0, help_text='Author royalty percentage', max_digits=5)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax rate applied (5% culture, 10% other)', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax amount withheld', max_digits=10)),
                ('is_taxable', models.BooleanField(default=False, help_text='Whether tax was applied')),
                ('final_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Final amount to be paid to author (after tax)', max_digits=10)),
                ('status', models.CharField(choices=[('calculated', 'Calculated'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='calculated', help_text='Payment status', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, help_text='External transaction reference', max_length=100, null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When the payment was made', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the payment was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the payment was last updated')),
                ('author', models.ForeignKey(help_text='Author receiving the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(help_text='Book that generated the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='books.book')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_reference', models.CharField(help_text='Unique batch reference', max_length=50, unique=True)),
                ('payment_method', models.CharField(choices=[('telebirr', 'Telebirr'), ('cbe', 'CBE Birr'), ('bank_transfer', 'Bank Transfer')], default='telebirr', help_text='Payment method for this batch', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount in this batch', max_digits=12)),
                ('total_payments', models.IntegerField(default=0, help_text='Number of payments in this batch')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Batch status', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the batch was processed', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the batch was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the batch was last updated')),
                ('processed_by', models.ForeignKey(blank=True, help_text='User who processed this batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Purchase amount', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', help_text='Purchase status', max_length=20)),
                ('payment_method', models.CharField(choices=[('telebirr', 'Telebirr'), ('cbe', 'CBE Birr'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], default='telebirr', help_text='Payment method used', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Unique transaction ID', max_length=50, null=True, unique=True)),
                ('transaction_reference', models.CharField(blank=True, default=None, help_text='External transaction reference', max_length=100, null=True)),
                ('purchase_reference', models.CharField(blank=True, default=None, help_text='Purchase reference', max_length=100, null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the purchase was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the purchase was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the purchase was last updated')),
                ('book', models.ForeignKey(help_text='Book that was purchased', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='books.book')),
                ('user', models.ForeignKey(help_text='User who made the purchase', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Transaction amount', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', help_text='Transaction status', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, help_text='External transaction reference', max_length=100, null=True)),
                ('response_data', models.JSONField(blank=True, help_text='Raw response from payment gateway', null=True)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if transaction failed')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the transaction was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the transaction was created')),
                ('batch', models.ForeignKey(help_text='Batch this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.paymentbatch')),
                ('payment', models.ForeignKey(help_text='Payment this transaction is for', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.payment')),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='purchase',
            field=models.ForeignKey(blank=True, help_text='Purchase that generated this payment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.purchase'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['user', 'status'], name='purchases_user_id_5d2dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['book', 'status'], name='purchases_book_id_1bd5f5_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['transaction_id'], name='purchases_transac_917217_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['transaction_reference'], name='purchases_transac_1cc811_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['purchase_reference'], name='purchases_purchas_af9a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['created_at'], name='purchases_created_41e89e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['batch', 'status'], name='payment_tra_batch_i_adb283_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment'], name='payment_tra_payment_6366f0_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_reference'], name='payment_tra_transac_98516a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentbatch',
            index=models.Index(fields=['batch_reference'], name='payment_bat_batch_r_7cbbc7_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentbatch',
            index=models.Index(fields=['status'], name='payment_bat_status_3e8882_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentbatch',
            index=models.Index(fields=['created_at'], name='payment_bat_created_22921a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['author', 'status'], name='payments_author__feaef1_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['book'], name='payments_book_id_c8f80e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payments_created_e3a130_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_status_d621e5_idx'),
        ),
    ]
