# Generated by Django 4.2.7 on 2026-09-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_financesettings_financereport'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='financereport',
            new_name='finance_rep_period__105cbe_idx',
            old_name='finance_rep_period__idx',
        ),
        migrations.AlterField(
            model_name='paymentbatch',
            name='payment_method',
            field=models.CharField(choices=[('telebirr', 'Telebirr'), ('chapa', 'Chapa'), ('paypal', 'PayPal'), ('cbe', 'CBE Birr'), ('bank_transfer', 'Bank Transfer')], default='telebirr', help_text='Payment method for this batch', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('telebirr', 'Telebirr'), ('chapa', 'Chapa'), ('paypal', 'PayPal'), ('cbe', 'CBE Birr'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], default='telebirr', help_text='Payment method used', max_length=20),
        ),
    ]
