# Generated by Django 4.2.7 on 2026-06-13 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('language', models.CharField(choices=[('English', 'English'), ('Amharic', 'Amharic'), ('Arabic', 'Arabic'), ('French', 'French'), ('German', 'German'), ('Spanish', 'Spanish')], default='English', max_length=20)),
                ('edition', models.CharField(default='1', max_length=50)),
                ('page_count', models.IntegerField(default=0)),
                ('publication_year', models.IntegerField(default=2024)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_free', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='books/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('sample_file', models.FileField(blank=True, null=True, upload_to='samples/')),
                ('keywords', models.TextField(blank=True, default='')),
                ('downloads_count', models.IntegerField(default=0)),
                ('purchase_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('in_review', 'In Review'), ('needs_revision', 'Needs Revision'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='pending_review', max_length=20)),
                ('revision_notes', models.TextField(blank=True, default='')),
                ('revision_attempts', models.IntegerField(default=0)),
                ('submitted_for_review_at', models.DateTimeField(blank=True, null=True)),
                ('checker_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('maker_approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.genre')),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='books.book')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wishlists',
                'unique_together': {('client', 'book')},
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author'], name='books_author__4f60e0_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['genre'], name='books_genre_i_0fe7c3_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['status'], name='books_status_08b8fa_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['created_at'], name='books_created_a6d93f_idx'),
        ),
    ]
