# Generated by Django 4.2.7 on 2026-07-04 07:14

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(blank=True, default='', help_text='Full name of the user', max_length=255)),
                ('national_id', models.CharField(blank=True, help_text='16-digit National ID number', max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be exactly 16 digits.', regex='^\\d{16}$')])),
                ('national_id_verified', models.BooleanField(default=False, help_text='Whether the national ID has been verified')),
                ('phone', models.CharField(blank=True, default='', help_text='Phone number in format 09XXXXXXXX', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits starting with 09.', regex='^09\\d{8}$')])),
                ('phone_verified', models.BooleanField(default=False, help_text='Whether the phone number has been verified')),
                ('address', models.TextField(blank=True, default='', help_text='Physical address of the user')),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', help_text='Gender of the user', max_length=10)),
                ('region', models.CharField(blank=True, default='', help_text='Region or state', max_length=100)),
                ('zone', models.CharField(blank=True, default='', help_text='Zone or sub-city', max_length=100)),
                ('woreda', models.CharField(blank=True, default='', help_text='Woreda or district', max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('checker', 'Content Checker'), ('maker', 'Content Maker'), ('author', 'Author'), ('client', 'Client')], default='client', help_text='User role in the system', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the user account is active')),
                ('email_verified', models.BooleanField(default=False, help_text='Whether the email has been verified')),
                ('email_verification_token', models.CharField(blank=True, default='', help_text='Token for email verification', max_length=255)),
                ('verification_token_expires', models.DateTimeField(blank=True, help_text='Expiration time for verification token', null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='IP address of last login', null=True)),
                ('last_seen', models.DateTimeField(blank=True, help_text='Last time the user was seen', null=True)),
                ('profile_image', models.ImageField(blank=True, help_text='Profile image of the user', null=True, upload_to='profiles/')),
                ('bio', models.TextField(blank=True, default='', help_text='Short biography of the user')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the user was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the user was last updated')),
                ('locked_until', models.DateTimeField(blank=True, help_text='Account lockout expiration time', null=True)),
                ('login_attempts', models.IntegerField(default=0, help_text='Number of failed login attempts')),
                ('two_factor_enabled', models.BooleanField(default=False, help_text='Whether 2FA is enabled for the user')),
                ('two_factor_verified', models.BooleanField(default=False, help_text='Whether 2FA has been verified during current session')),
                ('two_factor_secret', models.CharField(blank=True, default='', help_text='Secret key for TOTP 2FA', max_length=255)),
                ('two_factor_backup_codes', models.TextField(blank=True, default='', help_text='Comma-separated backup codes for 2FA')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='', help_text="Client's phone number", max_length=20)),
                ('national_id_verified', models.BooleanField(default=False, help_text='Whether the national ID has been verified')),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Wallet balance', max_digits=10)),
                ('total_purchases', models.IntegerField(default=0, help_text='Total number of purchases')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount spent', max_digits=10)),
                ('preferred_genres', models.TextField(blank=True, default='', help_text='Comma-separated list of preferred genres')),
                ('newsletter_subscribed', models.BooleanField(default=True, help_text='Whether the client is subscribed to newsletter')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the profile was last updated')),
                ('user', models.OneToOneField(help_text='The user associated with this client profile', on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clients',
                'indexes': [models.Index(fields=['created_at'], name='clients_created_4c189f_idx'), models.Index(fields=['user_id'], name='clients_user_id_ac8513_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='', help_text='Detailed author biography')),
                ('website', models.URLField(blank=True, default='', help_text="Author's personal website")),
                ('author_pseudonym', models.CharField(blank=True, default='', help_text='Pen name or pseudonym', max_length=100)),
                ('facebook_url', models.URLField(blank=True, default='', help_text='Facebook profile URL')),
                ('twitter_url', models.URLField(blank=True, default='', help_text='Twitter/X profile URL')),
                ('instagram_url', models.URLField(blank=True, default='', help_text='Instagram profile URL')),
                ('linkedin_url', models.URLField(blank=True, default='', help_text='LinkedIn profile URL')),
                ('bank_account_name', models.CharField(blank=True, default='', help_text='Name on bank account', max_length=100)),
                ('bank_account_number', models.CharField(blank=True, default='', help_text='Bank account number', max_length=50)),
                ('bank_name', models.CharField(blank=True, default='', help_text='Name of the bank', max_length=100)),
                ('tax_id', models.CharField(blank=True, default='', help_text='Tax identification number', max_length=50)),
                ('tin_number', models.CharField(blank=True, default='', help_text='TIN number', max_length=20)),
                ('author_image', models.ImageField(blank=True, help_text='Author profile image', null=True, upload_to='authors/')),
                ('agreement_signed', models.BooleanField(default=False, help_text='Whether the author has signed the agreement')),
                ('agreement_signed_at', models.DateTimeField(blank=True, help_text='When the agreement was signed', null=True)),
                ('verification_status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_submitted', help_text='Verification status of the author', max_length=20)),
                ('verification_documents', models.TextField(blank=True, default='', help_text='Documents submitted for verification')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the author was verified', null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=70.0, help_text='Commission rate percentage', max_digits=5)),
                ('total_royalties_earned', models.DecimalField(decimal_places=2, default=0.0, help_text='Total royalties earned', max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount paid to author', max_digits=10)),
                ('pending_payout', models.DecimalField(decimal_places=2, default=0.0, help_text='Pending payout amount', max_digits=10)),
                ('last_payment_date', models.DateTimeField(blank=True, help_text='Date of last payment', null=True)),
                ('total_books_published', models.IntegerField(default=0, help_text='Total number of books published')),
                ('total_downloads', models.IntegerField(default=0, help_text="Total downloads of author's books")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the profile was last updated')),
                ('agreement_version', models.CharField(default='1.0', help_text='Version of the agreement signed', max_length=20)),
                ('author_signature', models.CharField(blank=True, help_text='Digital signature of the author', max_length=100, null=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating of the author', max_digits=3)),
                ('user', models.OneToOneField(help_text='The user associated with this author profile', on_delete=django.db.models.deletion.CASCADE, related_name='author_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Who verified the author', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_authors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'author_profiles',
                'indexes': [models.Index(fields=['verification_status'], name='author_prof_verific_1cf0f7_idx'), models.Index(fields=['created_at'], name='author_prof_created_2ffcc3_idx'), models.Index(fields=['user_id'], name='author_prof_user_id_d1d456_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone'], name='users_phone_af6883_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['national_id'], name='users_nationa_4aa388_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['two_factor_enabled'], name='users_two_fac_74d74d_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['two_factor_verified'], name='users_two_fac_6425dd_idx'),
        ),
    ]
