# Generated by Django 4.2.7 on 2026-08-11 14:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('checker', 'Checker Review'), ('maker', 'Maker Review'), ('admin', 'Admin Review')], default='checker', max_length=20)),
                ('content_quality', models.DecimalField(decimal_places=1, default=0, help_text='Content quality score (0-10)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('editorial_quality', models.DecimalField(decimal_places=1, default=0, help_text='Editorial quality score (0-10)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('technical_quality', models.DecimalField(decimal_places=1, default=0, help_text='Technical quality score (0-10)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('copyright_compliance', models.DecimalField(decimal_places=1, default=0, help_text='Copyright compliance score (0-10)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('community_guidelines', models.DecimalField(decimal_places=1, default=0, help_text='Community guidelines score (0-10)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('overall_score', models.DecimalField(decimal_places=1, default=0, help_text='Overall quality score (0-10)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('comments', models.TextField(blank=True, default='')),
                ('recommendation', models.CharField(choices=[('approved', 'Approved'), ('needs_revision', 'Needs Revision'), ('rejected', 'Rejected')], default='needs_revision', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_reviews', to='books.book')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quality_reviews',
                'ordering': ['-created_at'],
                'unique_together': {('book', 'reviewer', 'review_type')},
            },
        ),
    ]
