# Generated by Django 4.2.7 on 2026-07-03 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('checker', 'Checker Review'), ('maker', 'Maker Review')], default='checker', max_length=10)),
                ('content_quality', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('editorial_quality', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('technical_quality', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('comments', models.TextField(blank=True, default='')),
                ('recommendation', models.CharField(blank=True, choices=[('approved', 'Approved'), ('needs_revision', 'Needs Revision'), ('rejected', 'Rejected')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quality_reviews',
                'indexes': [models.Index(fields=['book'], name='quality_rev_book_id_36385c_idx'), models.Index(fields=['reviewer'], name='quality_rev_reviewe_8db094_idx')],
                'unique_together': {('book', 'review_type')},
            },
        ),
    ]
